POST https://node-do-zero-hqr7.onrender.com/videos
Content-Type: application/json

{
    "title": "video 03",
    "description": "video 03",
    "duration": 180    
}

###

GET https://node-do-zero-hqr7.onrender.com/videos

###

PUT https://node-do-zero-hqr7.onrender.com/videos/07d4f610-2469-4a15-9b07-47820151934f
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é o primeiro video",
    "duration": 180    
}

###

DELETE https://node-do-zero-hqr7.onrender.com/videos/07d4f610-2469-4a15-9b07-47820151934f